spring:
  datasource:
    url: https://dpg-cov7go021fec73fg118g-a.frankfurt-postgres.render.com/ecommerce_h67e
    username: ecommerce_h67e_user
    password: pNkt0IhkfreFXqVgONdTALqPb1HoPpcT

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.mail.ru
    port: 465
    username: furniture_commerce@mail.ru
    password: 0kDSsUEA2Bvyh09qNtWt
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

application:
  security:
    jwt:
      secret-key: 34743777217A25432A462D4A614E645267556B58703273357638782F413F4428
      expiration: 900_000
      refresh-token:
        expiration: 2_592_000_000
  paths:
    images: /app/images/
